### ISSUE TITLE
Deciding on an engine to lock into

### ISSUE THREAD

**Issue by jrslagle** [Master-Foo/game#23]

**Comment by jrslagle** [comment]
@Master-Foo, what are your thoughts on unity?

**Comment by Master-Foo** [comment]
Unity is an engine for Script Kiddies and Pointy Haired Bosses and Limp Dicked Cuckolds.

Instead of just saying "We need to find a better engine than pygame" Why don't you give some reasons for doing so first? My feeling on the matter is, the reason goes something like this

"Unitiy gots electrolytes!"

Jimmy... Do plants crave Unity? Do they really?

I'm currently looking at some other options. But, at this juncture, the game engine doesn't matter. We can do what we currently need to do with any game engine and pygame is a good place to start.

**Comment by Master-Foo** [comment]
Here is the concession I am willing to make to anyone who wants to use Unity. A [professional license](https://store.unity.com/) is $125 per person per month. If anyone wants this to happen they should put their money where there mouth is and cough up the cash to buy everyone on the team a license for 1 year.

Or... We can use FOSS.

Now is the time to prove how much you like Unity.

**Comment by fishscene** [comment]
I ran across this:
http://www.worldofleveldesign.com/categories/level_design_tutorials/recommended-game-engines.php

It provides an overview of a bunch of game engines.

I also wanted to point out this video concerning planetary procedural generation:
https://www.youtube.com/watch?v=XuDj5v81Nd0 (Timecode 1 hour, 57 minutes), where they go over a bit of the planetary tech they are using for this game. They are using the Amazon Lumberyard platform, (They moved to it due to limitations of adapting CryEngine, but they couldn't talk about it until just a few days ago - well after this video was made).. This is a company with millions of dollars to pull this off, but I figured we could dream a bit ;)

**Comment by jrslagle** [comment]
@fishscene, that terrain generation and flying in and out of the planet was awesome! But yea, that's what 360 developers gets you.

**Comment by jrslagle** [comment]
@Master-Foo decided all other engines are either too closed source, or don't allow development on Linux. Thus we are staying with PyGame until death.
