### ISSUE TITLE
WHY DOES THIS GAME USE 60% OF MY CPU WHEN I'M STANDING STILL?! 

### ISSUE THREAD

**Issue by jrslagle** [Master-Foo/game#26]
General discussion, ideas, and inspiration for budding off smaller optimization projects. 

One is the keyboard listener polling every frame. (#25)

Another is the animating single frames (#10)

And I believe the tiles are being re-chosen every frame if I overheard correctly.

**Comment by Master-Foo** [comment]
No matter how efficient we make this game, it will ALWAYS hog your CPU because the game loop is CPU bound. If it is only taking 60% of yours, you are lucky. The real metric for determining how inefficient this game is, is **"How many frames per second can I draw?"** and **"How much memory is being used"**

However, just because cpu hogging is expected, doesn't mean it can't be streamlined.

* The keyboard polling, I can guarantee you isn't what is hogging your CPU. The processing power required to make that work in a drop in the bucket compared to everything else that is going on.

* Animating sprites that don't need to be animated is probably a big one.

* The re-choosing of the tiles is actually the one thing that allows the entire Hectare to be loaded. The alternative is load all tiles in the Hectare and render all 10,000 of them. It's cheaper to select only the 100 closest tiles and render them. One improvement might be to only grab those tiles for every 1 meter you walk as opposed to every frame.

If anyone wants to figure these things out. Do it. I'm too busy working on getting the system together in general to look at specifics.

Also, we are in prototyping phase. The code isn't supposed to be graceful right now, nor a priority. A slow code base that is actually a game is better than a fast code base with no objectives.

I'm removing "Bug Status" from this issue, because this isn't a bug. It's an enhancement.

**Comment by jrslagle** [comment]
@Master-Foo, do you know if the tiles are still rechosen every frame, or every meter moved? If every frame, I'd like to make an issue for it and close this one out.

**Comment by Master-Foo** [comment]
It's still chosen every frame. But, as I said before, that isn't the reason why CPU gets maxed out. It gets maxed out because the gameloop itself will use up all the CPU it can.

If you want confirmation, run this script.

```python
while True:
    pass
```

This does nothing complicated, but will still consume your entire CPU.
