### ISSUE TITLE
Create a Tomato

### ISSUE THREAD

**Issue by Master-Foo** [Master-Foo/game#29]
I made a Corn Entity it grows over the course of about a minute. Look at that and create a new entity for a tomato. The images ready exist.

Pro tip: This is really super stupid and simple. Don't do anything fancy. Don't submit anything that doesn't have anything to do with the tomato. Start a new project clone without all the garbage. make a branch called "tomato"

``` bash
git branch tomato
```

make a tomato

then submit that for review. Don't submit ANYTHING ELSE except for a couple of files pertaining to the damn tomato. No .idea folders, no code you copied from someone else, no code from other issues you are working on. JUST the code from your tomato branch.

You'll probably be able to have this done and submitted and approved in 1 hour's worth of work.

**Comment by fishscene** [comment]
I'll see if I can whip something up tomorrow. Super tired tonight. :/

**Comment by fishscene** [comment]
So I'm realizing my artwork is about 2nd-grade level. But I'm assuming we just need a stand-in, so I'm moving forward.

Should the files be named exactly the same as the ones they are replacing? For example, the original is "000.png", should I name my replacement as "000.png"?

**Comment by fishscene** [comment]
I think I got confused with the original request and created a bunch of artwork instead of code. If it helps anyone:
https://github.com/Master-Foo/game/commits/master
This helped me dig up the changes for the corn commit, so I knew what files to modify to make the tomato.

I couldn't figure out how to start a new clone and I may have some junk in the commit log, not sure if that's ok or not. I'm pretty new when it comes to using git and github. If something is off, please let me know and/or reject the PR and I'll try to figure out how to clean it up.

**Comment by fishscene** [comment]
Figured out what I did wrong with creating a clean commit. I closed out my unclean PR and submitted a new PR.

**Comment by Master-Foo** [comment]
That was a good commit.

If you want to continue down this line, we could use an intermediary class called Plant that all plants inherit from. You can make that. IIRC, My corn and your tomato inherit from Inanimate. Corn and Tomato (and others) should inherit from Plant and Plant should inherit from Inanimate. Move similar redundant code from both Corn and Tomato into Plant.
