### ISSUE TITLE
Choose a Camera Type

### ISSUE THREAD

**Issue by jrslagle** [Master-Foo/game#53]
This needs to be decided before we can make the art.

**1st person** - common in shooters, scary games, and VR. Use 1st person when the game is enhanced by feeling like you're there.
Cons - art needs to look really good up close. can get motion sickness. can't see dangers behind you.
Pros - feels more immersive. can show off the bottomless detail offered by procedurally generated textures. can't see dangers behind you.

**3rd person follow** (either the player controls the camera or the game does). Common in RPGs, platform. Used when you want to be able to look in any direction AND get a better view of your avatar's situation.
Cons - camera control is hard. Can get the camera stuck behind or inside geometry, and its easy for the player to stick the camera where they shouldn't.
Pros - can see what's behind you. have more of a situational view.

**3rd person isometric** - like Diablo, StarCraft or the Sims. Good for games where the draw is less about immersion and more about managing tasks.
Cons - it's not very immersive.
Pros - art only needs to accommodate the closest you'll zoom. Barriers that obscure view can be ghosted to see through them. The camera can't make your game look ugly. You can see your whole situation in all directions.

**Comment by jrslagle** [comment]
I'm personally on the fence between 1st person for the immersion and 3rd person isometric for how easy it makes art and camera stuff, and seeing behind you.

**Comment by jrslagle** [comment]
You know. If our art was detailed, 1st person isn't a hard camera to manage. I'd love an in game option to right click on your avatar or one of your bots and "Go 1st person". And from there have the option "Return to Isometric View".

**Comment by jrslagle** [comment]
Your HUD might change a little, but all the actions should stay the same, for simplicity.

**Comment by jrslagle** [comment]
@Master-Foo 
So... I'm okay with doing this game in 2.5 D. And I mean a 45* angle view with sprites for graphics - like StarCraft. I don't see losing any functionality, and it really cuts down on the needed work - code and art. 

Things that I think would still be 3D are jumping and physics. Terrain and elevation. The models used to make rotated views of Animate's sprites. And that's it?

**Comment by Master-Foo** [comment]
In the long term going 3D is going to save us work. Why? Because when you create new actions and animations with sprites, you need to create each frame from scratch, whereas with 3D, you can just use the same model and just add an animation script to it.

Likewise, if you have multiple characters, like NPCs or other players you need to make all those actions and animations from scratch for them from scratch as well. Where as, if we are going 3D, you can make a model for them and still use the same animation scripts.

3D has a high barrier to entry, but once the cost has been paid, it is far more reusable and is more cost effective afterwards.

I think the main concern in deciding whether we go 3D or 2D is, "Who the fuck is going to do it?". I'm not talking about the 3D engine here. I can do that. What I'm talking about is the art resources. I just have too much on my plate to spend my time on art. So, if someone wants to be the "Art Guy" 2D or 3D, that person is largely going to determine what direction this project takes.

So, I'm not going to argue in favor of 2D or 3D. What I'm going to do is wait for someone to step up and take charge and let them make the decision based on the amount of work they are willing to do to make their ideas for this game a reality.

**Comment by jrslagle** [comment]
You're right, the art we get should be the deciding factor on HOW 3D we get. And yea, no matter what, we're going to need 3D models of anything animated or rotatable just to create the sprites.

I've been toying with the idea of diving into Blender these last couple days. I haven't yet because I also have tasks assigned I don't want to neglect. Also, what I want to get out of this project is programming job skills. Actually, I've been researching the actuarian profession and love it. I'd like to keep my tasks here somewhat applicable to that, given the option. Going into CGI - while super interesting and an old hobby - is a profession unto itself. That said, it's hard not to frolic in the awesome world of 3D graphics.

**Comment by jrslagle** [comment]
We've settled on front view, square grid, 2.5 D, keeping the view we already have. Switching to a diagonal 2.5 D view would be an undertaking without enough return, and 3D is even more difficult without a dedicated experienced modeler. 

Any objects that are tall enough to block the view of the character, should ghost so you can see the avatar.
